RedHatInsights/insights-upload

- Jenkinsfile
- requirements.txt
Modified Jenkins pipeline to generate xunit test coverage report and save test results artifacts.
This change was applied to *qe branch* and has been tested on internal Jenkins.
> Modified Jenkins Pipeline to generate unit test coverage

- README.md
> Document MQ fields

- .gitignore
- README.md
- app.py
- docker/consumer/app.py
- tests/fixtures/__init__.py
- tests/fixtures/fake_mq.py
- tests/test_app.py
Update names in the message queue to align with new naming convention.
Update tests as well
> Update message queue names

- app.py
- tests/test_app.py
This patch attempts to factor out the tedious error handling for kafka clients.
One functional change is for the producer, rather than looping over all the
items currently in the local queue, one item per cycle will be processed, but
there is no sleep unless the local queue is empty.
I've validated the refactoring idea in a dummy script, but not against the real
kafka clients, so that needs to be done before this PR is merged.
> refactoring the way the mq client loops work

- app.py
- tests/test_app.py
- utils/storage/s3.py
> Bump s3 archive URL TTL up to 1hr

- app.py
Added an extra field for logging so that you can query upload-service
messages using the payload_id. Great for troubleshooting an individual
upload.
query: `payload_id: <string>`
Fixes #102
> Make payload_id an index in kibana

- app.py
- tests/test_app.py
- utils/mnm.py
- utils/storage/s3.py
Need S3 metrics to show how much time is spent copying files around
S3 buckets
> add S3 metrics for providing time

- app.py
Generate a request ID during local development or if 3scale is otherwise bypassed and does not assign one
> Generate requestID

- app.py
We need to be able to search for the inventory ID when upload-service receives metadata and posts to inventory.
Also fixed a couple minor things
> Add log message for upload posts to inventory

- app.py
- tests/conftest.py
- tests/test_app.py
multiple posts to inventory get a different stauts code
need to clean this up further but this will fix an issue in CI
Also need to clean up the tests
> Fix bug in inventory post

- app.py
Log more information about the host that failed to post to the inventory service.
@SteveHNH I did not test this as I didn't have time to setup the upload-service locally, etc.  Feel free to throw this away and fix it how you like.  This is really just a placeholder for an idea.
> Log more info about the host that failed to post to the inventory service

- app.py
> Metadata is passed in the files, not the body_arguments

- Pipfile
- Pipfile.lock
- README.md
- app.py
- requirements.txt
- spec.yaml
- tests/test_app.py
Get the latest changes to stable. The API stuff is apparently going in early so want to get this tested and make sure it's good to go
> Merge to stable

- app.py
- tests/conftest.py
- tests/test_app.py
- tests/test_storages.py
- utils/config.py
Moved a bunch of env variables to a config file to make this more
readable.
Added the account number to log message since we need to be able to
search this.
> Move configurables to config file

- app.py
The current way we process messages from the validated
queue is actually serial.  This change lets us work on
blocks of validated messages at a time.  Most of the work
involves waiting on IO so we should see some speed up.
> Processing validated messages in parallel via gather()

- app.py
Signed-off-by: Jesse Jaggars <jjaggars@redhat.com>
> account number is optional

- app.py
send logs from tornado to cloudwatch
> Add tornado application logs to cloudwatch

- app.py
Without a queue we wont' process anything and send it to kafka. We need
to know if this happens.
> Log if a queue is not established

- app.py
- remove mixed data types in logger arguments
- add cloudwatch handler to each logger individually
> Fix logging to cloudwatch

- app.py
- tests/app/test_upload_handler.py
- utils/config.py
commit_date and valid_topics should be more forgivable if either of
those things don't exist. We were doing this with DEVMODE but it's more
appropriate just to wrap them in try/except so that we can startup in a
dev environment even if we don't have these vars available.
This will particularly make local dev easier to get started.
> Remove DEVMODE variable

- app.py
We had no logs for when we actually send a message onto the queue
> Add succeed log for when messages are placed on mq
